In [1]:
#DBM
import numpy as np

def sigmoid(x): return 1 / (1 + np.exp(-x))
def sample(prob): return np.random.binomial(1, prob)
def sample_layer(x, W, b):
    prob = sigmoid(np.dot(x, W) + b)
    return sample(prob), prob

def dbm_step(v, W1, b1, W2, b2, lr=0.01):
    h1, _ = sample_layer(v, W1, b1)
    h2, h2_prob = sample_layer(h1, W2, b2)
    h1_rec, _ = sample_layer(h2, W2.T, np.zeros_like(b1))
    v_rec, _ = sample_layer(h1_rec, W1.T, np.zeros_like(v))

    W1 += lr * (np.outer(v, h1) - np.outer(v_rec, h1_rec))
    W2 += lr * (np.outer(h1, h2) - np.outer(h1_rec, h2))
    b1 += lr * (h1 - h1_rec)
    b2 += lr * (h2 - h2_prob)
    return W1, b1, W2, b2

# Initialize
np.random.seed(42)
v = np.array([1, 0, 1, 0])
W1, b1 = np.random.randn(4, 3) * 0.1, np.zeros(3)
W2, b2 = np.random.randn(3, 2) * 0.1, np.zeros(2)

# Training step
W1, b1, W2, b2 = dbm_step(v, W1, b1, W2, b2)

print("W1:\n", W1, "\nb1:", b1, "\nW2:\n", W2, "\nb2:", b2)


W1:
 [[ 0.05967142 -0.01382643  0.07476885]
 [ 0.15230299 -0.02341534 -0.0234137 ]
 [ 0.16792128  0.07674347 -0.03694744]
 [ 0.054256   -0.05634177 -0.04657298]] 
b1: [0.01 0.   0.01] 
W2:
 [[ 0.03419623 -0.19132802]
 [-0.17249178 -0.05622875]
 [-0.09128311  0.03142473]] 
b2: [ 0.00562073 -0.00446176]
